version: '3'

services:

  node:
    build:
      context: .
      dockerfile: Node.Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    image: jwthomas/album-reviews-frontend-node
