version: '2'

include: 
  - ./login-page-backend/docker-compose.yml

services:

  frontend-node:
    build:
      context: login-page-frontend
      dockerfile: Dev.Dockerfile
    env_file:
      - ./login-page-frontend/.env
    volumes:
      - $PWD/login-page-frontend/:/usr/src/app
    ports:
    #  - 80:80
      - 3000:3000
    image: jwthomas/login-page-frontend-node

  backend-node:
    build:
      context: login-page-backend
    depends_on:
      - laravel.test
    #   dockerfile: Dockerfile
    # env_file:
    #   - ./login-page-backend/.env
    # volumes:
    #   - $PWD/login-page-backend/app:/usr/src/app
    # ports:
    #   - 8080:8080
    # image: jwthomas/login-page-backend-node:latest
