include: 
  - ./login-page-backend/docker-compose.yml

services:

  frontend-node:
    build:
      context: login-page-frontend
      dockerfile: Dev.Dockerfile
    env_file:
      - ./login-page-frontend/.env
    volumes:
      - $PWD/login-page-frontend/:/usr/src/app
    ports:
      - 3000:3000
    image: jwthomas/login-page-frontend-node

  backend-node:
    build:
      context: login-page-backend
    depends_on:
      - laravel.test
